meta_product_name: "Ordify"
meta_title: "Ordify Digitizing the dining experience"
meta_description: "Digitizing the dining experience through mobile ordering and checkout system"
meta_image: "img2.jpg"
